name: merge

# configure as reusable workflow
on:
  workflow_call:
    inputs:
      target_branch:
        required: true
        type: string
      source_branch:
        required: true
        type: string
      bot_name:
        required: false
        type: string
        default: "Super Bot"
      bot_mail:
        required: false
        type: string
        default: bot@feedgy.solar
    secrets:
      GITHUB_TOKEN:
        required: false
        description: "token to have access to code repository and registry (passed by caller workflow)"

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ inputs.target_branch }}
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: "merge branch"
        run: |
          git config --local user.email '${{ inputs.bot_mail }}'
          git config --local user.name '${{ inputs.bot_name }}'
          git merge ${{ inputs.source_branch }} --no-ff --no-edit
          git push