name: release

# configure as reusable workflow
on:
    workflow_call:
        inputs:
            app_name:
                required: true
                type: string
                description: 'name of the application in argocd'
            registry:
                required: false
                type: string
                default: 'ghcr.io'
                description: 'registry to push and get the image'
            image_name:
                required: true
                type: string
                description: 'name of the image'
            docker_context:
                required: false
                type: string
                default: .
                description: 'context of build for docker'
            docker_build_args:
                required: false
                type: string
                description: 'docker build args formated in multiline string with |'
            dockerfile_path:
                required: false
                type: string
                default: ./Dockerfile
                description: 'location to get the Dockerfile for the build'
            username:
                required: true
                type: string
                description: 'username to push the image can use github.actor'
            pre_release_branches:
                required: false
                type: string
                default: staging
                description: 'comma separated list of pre release branches'
            release_branches:
                required: false
                type: string
                default: production
                description: 'comma separated list of release branches'
            branch:
                required: true
                type: string
                description: 'name of the branch can use github.ref_name'
            infra_repository:
                required: true
                type: string
                description: 'repository of the infra project'
            infra_main_branch:
                required: false
                type: string
                default: master
                description: 'default branch for the infra repository'
            push_name:
                required: false
                type: string
                default: 'Super Bot'
                description: 'name of the user who will push on infra repository'
            push_mail:
                required: false
                type: string
                default: 'bot@feedgy.solar'
                description: 'mail of the user who will push on infra repository'
            dry_run:
                required: false
                type: boolean
                default: false
                description: 'build only with the new version of tag'
        secrets:
            registry_token:
                required: true
                description: 'token to have access to registry'
            repos_token:
                required: true
                description: 'token to have access to code and infra repository'


jobs:
    tag:
        uses: ./tag.yml
        with:
            pre_release_branches: ${{ inputs.pre_release_branches }}
            release_branches: ${{ inputs.release_branches }}
            dry_run: ${{ inputs.dry_run }}
        secrets:
            repos_token: ${{ secrets.repos_token }}
    build:
        uses: ./build-docker.yml
        needs:
            - tag
        with:
            registry: ${{ inputs.registry }}
            image_name: ${{ inputs.image_name }}
            docker_context: ${{ inputs.docker_context }}
            docker_build_args: ${{ inputs.docker_build_args }}
            dockerfile_path: ${{ inputs.dockerfile_path }}
            username: ${{ inputs.username }}
            branch: ${{ inputs.branch }}
            tag: ${{ needs.tag.new_tag }}
            dry_run: ${{ inputs.dry_run }}
        secrets:
            registry_token: ${{ source.registry_token }}
    deploy-and-release:
        uses: ./deploy-app.yml
        needs:
            - tag
            - build
        with:
            app_name: ${{ inputs.app_name }}
            image_name: ${{ inputs.image_name }}
            username: ${{ inputs.username }}
            branch: ${{ inputs.branch }}
            infra_repository: ${{ inputs.infra_repository }}
            infra_main_branch: ${{ inputs.infra_main_branch }}
            push_name: ${{ inputs.push_name }}
            push_mail: ${{ inputs.push_mail }}
            tag: ${{ needs.build.outputs.tag }}
            changelog: ${{ needs.tag.outputs.changelog }}
        secrets:
            repos_token: ${{ secrets.repos_token }}
