name: tag

# configure as reusable workflow
on:
    workflow_call:
        inputs:
            pre_release_branches:
                required: false
                type: string
                default: staging
                description: 'comma separated list of pre release branches'
            release_branches:
                required: false
                type: string
                default: production
                description: 'comma separated list of release branches'
            dry_run:
                required: false
                type: boolean
                default: false
                description: 'build only with the new version of tag'
        outputs:
            new_tag:
                value: ${{ jobs.tag.outputs.new_tag }}
            new_version:
                value: ${{ jobs.tag.outputs.new_version }}
            changelog:
                value: ${{ jobs.tag.outputs.changelog }}
        secrets:
            repos_token:
                required: true
                description: 'token to have access to code and infra repository'


jobs:
    tag:
        runs-on: ubuntu-latest
        outputs:
            new_tag: ${{ steps.tag_version.outputs.new_tag }}
            new_version: ${{ steps.tag_version.outputs.new_version }}
            changelog: ${{ steps.tag_version.outputs.changelog }}
        steps:
            -   uses: actions/checkout@v2
                with:
                    token: ${{ secrets.repos_token}}
            -   name: Bump version and push tag
                id: tag_version
                uses: mathieudutour/github-tag-action@v6.0
                with:
                    # use PAT token to enable to merge production in master at release
                    github_token: ${{ secrets.repos_token}}
                    release_branches: ${{ inputs.release_branches }}
                    pre_release_branches: ${{ inputs.pre_release_branches }}
                    dry_run: ${{ inputs.dry_run }}